# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

references:
  known_hosts: &known_hosts
    run: 
      name: Add github ssh keys to known hosts 
      command: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts

  dependencies: &dependencies
    run:
      name: Download Dependencies
      command: |
        gem install bundler:2.2.17
        bundle config set --local path 'vendor/bundle'
        bundle install
        bundle clean --force
        bundle exec fastlane install_plugins

  restore_ruby_cache: &restore_ruby_cache
    restore_cache:
      keys: 
        - v4-gems-{{ checksum "Gemfile.lock" }}
        - v4-gems

  save_ruby_cache: &save_ruby_cache
    save_cache:
      key: v4-gems-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

  restore_spm_cache: &restore_spm_cache
    restore_cache:
        keys: 
          - v4-spm-{{ checksum "Kelo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}
          - v4-spm

  save_spm_cache: &save_spm_cache
    save_cache:
        key: v4-spm-{{ checksum "Kelo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved" }}
        paths:
          - SourcePackages

jobs:
  test:
    macos:
      xcode: 12.4.0
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - *known_hosts
      - *restore_ruby_cache
      - *dependencies
      - *save_ruby_cache
      - *restore_spm_cache
      - run: 
          name: Execute lane "test"
          command: bundle exec fastlane test
      - *save_spm_cache
      - codecov/upload:
          file: output/cobertura.xml
          token: $CODECOV_TOKEN
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  beta:
    macos:
      xcode: 12.4.0
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - *known_hosts
      - *restore_ruby_cache
      - *dependencies
      - *save_ruby_cache
      - *restore_spm_cache
      - run: 
          name: Execute lane "beta"
          command: bundle exec fastlane beta
      - *save_spm_cache
      - store_artifacts:
          path: output/Kelo.ipa

  release:
    macos:
      xcode: 12.4.0 
    working_directory: /Users/distiller/project
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - *known_hosts
      - *restore_ruby_cache
      - *dependencies
      - *save_ruby_cache
      - *restore_spm_cache
      - run: 
          name: Execute lane "release"
          command: bundle exec fastlane release
      - *save_spm_cache
      - store_artifacts:
          path: output/Kelo.ipa

workflows:
  test-pull-request:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master

  push-beta:
    jobs:
      - beta
      #     filters:
      #       tags:
      #         only: /^v.*-beta/
      #       branches:
      #         ignore: /.*/

  push-release:
    jobs:
      - release:
          filters:
            tags:
              only: /^((?!beta).)*$/
            branches:
              ignore: /.*/